# Generated by Django 5.0.3 on 2024-10-07 12:57

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_media_is_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, default=None, max_length=255, null=True, verbose_name='image'),
        ),
    ]
